name: Build Adjust Unity SDK

on: [push, pull_request]

jobs:
  buildUnity:
    name: Build on Unity ${{ matrix.unityVersion }} for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        unityVersion:
          #- 2018.4.36f1
          - 2020.3.9f1
        targetPlatform:
          - iOS
          - Android
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.unityVersion }}-
            Library-
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  buildXcode:
    name: Build iOS project generated by Unity ${{ matrix.unityVersion }}
    runs-on: macos-latest
    needs: buildUnity
    strategy:
      matrix:
        unityVersion:
          #- 2018.4.36f1
          - 2020.3.9f1
    steps:
      - name: Download iOS Artifact
        uses: actions/download-artifact@v2
        with:
          name: Build-${{ matrix.unityVersion }}-iOS
      - name: Build
        working-directory: iOS
        run: |
          xcodebuild build -project "Unity-iPhone.xcodeproj" -scheme "Unity-iPhone" -configuration "Release"
      - name: Cleanup generated Xcode project to avoid storage limit
        if: always()
        uses: geekyeggo/delete-artifact@v1
        with:
          name: Build-${{ matrix.unityVersion }}-iOS
